// ─────────────────────────────────────────────────────────────────────────────
// Push Notification Config — Generated by custom-push
// ─────────────────────────────────────────────────────────────────────────────
// This file is automatically kept in sync with our_pkg.json.
// Edit our_pkg.json to update these values.
// ─────────────────────────────────────────────────────────────────────────────

import ourPkg from '../../our_pkg.json';

export const pushConfig = {
  ...ourPkg.firebase,
  serviceWorkerPath: ourPkg.serviceWorker.path,
  registerUrl: ourPkg.backend.registerUrl || undefined,
};
