# 🚀 Quick Usage — generated by custom-push

To complete your push notification setup, follow these 3 simple steps:

### 1. Wrap your main Layout
In your `layout.tsx` (for Next.js) or `App.tsx`:

```tsx
import { CustomPushProvider } from 'custom-push';
import { pushConfig } from './notificationHandler/pushConfig';
import { PushNotificationManager } from './notificationHandler/PushNotificationManager';

export default function RootLayout({ children }) {
  return (
    <CustomPushProvider config={pushConfig}>
      {/* 💎 This component handles all foreground notifications */}
      <PushNotificationManager />
      {children}
    </CustomPushProvider>
  );
}
```

### 2. Add an "Enable Notifications" Button
In any component, you can use the `usePushMessage` hook to request permission and check the current status:

```tsx
import { usePushMessage } from 'custom-push';
import { Bell } from 'lucide-react'; // Or any icon library

export function NotificationToggle() {
  const { isPermissionGranted, requestPermission } = usePushMessage();

  const handleToggle = async () => {
    if (!isPermissionGranted) {
      await requestPermission();
    }
  };

  return (
    <button
      onClick={handleToggle}
      title={isPermissionGranted ? "Notifications enabled" : "Enable notifications"}
      style={{
        padding: '0.5rem',
        borderRadius: '50%',
        backgroundColor: isPermissionGranted ? '#7C3AED' : '#F3F4F6',
        color: isPermissionGranted ? '#FFFFFF' : '#6B7280',
        border: 'none',
        cursor: 'pointer'
      }}
    >
      <Bell style={{ 
        width: '1.25rem', height: '1.25rem', 
        fill: isPermissionGranted ? 'currentColor' : 'none' 
      }} />
    </button>
  );
}
```

### 3. Customizing Toasts
Open `src/push/notificationHandler/PushNotificationManager.tsx` and replace the `alert()` call with your preferred toast library (e.g. Sonner, React Hot Toast, or your own UI components).
